# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 194)
        MainWindow.setStyleSheet("")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 7, 0, 1, 1)
        self.vLabel = QtWidgets.QLabel(self.centralwidget)
        self.vLabel.setObjectName("vLabel")
        self.gridLayout.addWidget(self.vLabel, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 6, 0, 1, 1)
        self.wg_slider = QtWidgets.QSlider(self.centralwidget)
        self.wg_slider.setMinimum(100)
        self.wg_slider.setMaximum(65535)
        self.wg_slider.setProperty("value", 3000)
        self.wg_slider.setOrientation(QtCore.Qt.Horizontal)
        self.wg_slider.setObjectName("wg_slider")
        self.gridLayout.addWidget(self.wg_slider, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.dc_slider = QtWidgets.QSlider(self.centralwidget)
        self.dc_slider.setMinimum(100)
        self.dc_slider.setMaximum(65535)
        self.dc_slider.setProperty("value", 1000)
        self.dc_slider.setOrientation(QtCore.Qt.Horizontal)
        self.dc_slider.setObjectName("dc_slider")
        self.gridLayout.addWidget(self.dc_slider, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.cLabel = QtWidgets.QLabel(self.centralwidget)
        self.cLabel.setObjectName("cLabel")
        self.gridLayout.addWidget(self.cLabel, 3, 1, 1, 1)
        self.wLabel = QtWidgets.QLabel(self.centralwidget)
        self.wLabel.setObjectName("wLabel")
        self.gridLayout.addWidget(self.wLabel, 0, 2, 1, 1)
        self.dcLabel = QtWidgets.QLabel(self.centralwidget)
        self.dcLabel.setObjectName("dcLabel")
        self.gridLayout.addWidget(self.dcLabel, 1, 2, 1, 1)
        self.vLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.vLCD.setProperty("value", 1.0)
        self.vLCD.setObjectName("vLCD")
        self.gridLayout.addWidget(self.vLCD, 2, 2, 1, 1)
        self.cLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.cLCD.setObjectName("cLCD")
        self.gridLayout.addWidget(self.cLCD, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.wg_slider.sliderMoved['int'].connect(MainWindow.set_wavelength)
        self.dc_slider.sliderMoved['int'].connect(MainWindow.set_dc)
        self.pushButton.clicked.connect(MainWindow.start)
        self.pushButton_2.clicked.connect(MainWindow.stop)
        self.pushButton_3.clicked.connect(MainWindow.clear)
        self.pushButton_4.clicked.connect(MainWindow.reset)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GM Counter Controller"))
        self.label.setText(_translate("MainWindow", "Wavelength"))
        self.pushButton_4.setText(_translate("MainWindow", "RESET"))
        self.vLabel.setText(_translate("MainWindow", "-"))
        self.pushButton_3.setText(_translate("MainWindow", "CLEAR"))
        self.label_5.setText(_translate("MainWindow", "Counts"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "Duty Cycle"))
        self.label_3.setText(_translate("MainWindow", "Volts"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.cLabel.setText(_translate("MainWindow", "-"))
        self.wLabel.setText(_translate("MainWindow", "-"))
        self.dcLabel.setText(_translate("MainWindow", "-"))
from . import res_rc
