site_name: GM Counter - User Manual

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/gmc.png
  favicon: 'images/gmc.png'
  features:
    - navigation.footer
    - content.code.copy
  icon:
    annotation: material/arrow-right-circle 


#theme: 'readthedocs'

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - attr_list
    - def_list
    - md_in_html
    - smarty
    - attr_list
    - wikilinks
    - codehilite:
        linenums: False
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
       preserve_tabs: true
    - pymdownx.tabbed:
       alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css: ["assets/main.css"]
site_favicon: 'images/favicon.ico'

plugins:
   - search
   - table-reader
   #- page-to-pdf

extra:
  palette:
      primary: '#087da1'
      accent: '#00a889'


repo_name: 'cspark-gmcounter'
repo_url: 'https://github.com/csparkresearch/cspark-gmcounter'
copyright: 'Jithin B P'

site_url: https://csparkresearch.in/

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://x.com/csparkresearch
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/csparkresearch
    - icon: fontawesome/brands/github
      link: https://github.com/csparkresearch

nav:
  - Home: 'index.md'
  - Computer Interface: 'computer.md'

